language: d

services:
  - postgresql

before_script:
  - psql -c 'CREATE USER test' -U postgres
  - psql -c 'CREATE DATABASE test OWNER test' -U postgres

addons:
  apt:
    packages:
      - libpq-dev
